### ISSUE TITLE
add support for z80/6502 assemblers

### ISSUE THREAD

**Issue by rpolasek** [maziac/hex-hover-converter#11]
hello,

please add support for those old 8bit assemblers. a hex number starts with `$` and a binary number starts with `%` so you can use regular expressions below:

```typescript
const reSupported = /(?<!\w)([$%]?|[bBdDhH]{0,1}|(0x)?)?[0-9a-fA-F_]+([bBdDhH]{0,1}|([uU][lL])?)?\b/
const z80_hex = /^[$][0-9a-fA-F]+/.exec(hoveredWord)
const z80_bin = /^[%][01]+/.exec(hoveredWord)
```
you can find a working example at playground [here](https://www.typescriptlang.org/play/?pretty=true&ssl=48&ssc=1&pln=49&pc=1#code/MYewdgzgLgBATgUwMoFcAOaRyggJjAXhgHoAKAfgB4BCAHQHcBKUgbQBIBSAXXIB8WARgCFcAEQAWACS4BvAAwAaAIwBfXqTkAPRuR0s5AWgCcAQwMAzAIIGAYgH0uAalbCxU2YtXqWKAKpcWABsAGS4dHVoBYgAoaNBIWBxoJCg4AEswAHMIAC4YaHSsli5CGBZomEqYACIAYiU5Bqa5aoVK4mIYMBBYCHRMbDwYagqq6rZm5tb2zvEETRhSAC8ADjlGUcrqyca5cWmSWfnNmp2GyQOOmDnNE+qtM5a2q5u78UfLo9uqmskPtsO12OP2qHH+MxgAgyi1W6zuAnBgKhYDuQkRV2RdzkCN2U2enUxIMeAk+kIyd0eQlJhLGiMBuAQwDuuHRnQZTJBolZMHZFNxu1wpN5RP5DVEQsZfJ2KEC0yuwtporkvmCcrZkq4sXMWEW8Wg1xAADcEIhcAB1LD4EDmGBJKApQrZRgwGQnPWwMAoAC2pUQqAwWBwuAAdPNGaRxEaTXgLXBcBsfmkbaRqJ6vc7XT8fnqQIEEMHAiBMqQAAYySPG02x3AqGAmuBYEsJrOVeJQDIoBAnWsIQIQBAwJOLCvR82W4YEIhp-RhF0nbPgCC5-OF4sltjlqNVy21lBgADW3XoYBgG7TKib86qbY7XZ+KhOVzSEBgsK63oEJvIbsXsDfRGIAA9Vg2ACQxTAsawbCcRhvG4fQDCUGDiFDTRwxHbc42bSohxTWEMyvVtF2XAsi1LDcMJjHcYBAfdLxbIiwHbT07yqB8fifF83xud8vU-OBvwXBJXzWOweIAwD2DA4wzCsWwnBQsNgAjLcqKwk5cNhMT5hgAAyXSDUrNT8EnIgtJuGcCIYmAczzUi1wo1SxzjWtuJ0tN+PohibxY7tH06Z8RLkMkTw8r8f2ErTkVKICWHgxoFNQ9CnOrbDB2TKLoX0wzR2rQhJyCuxkUsudrNslcyPXTcjOcmsgpC3jPLSoTmM7PyOM6PdDxAY8IqXOzV3I6rcuorqjxPbU4C9EwoEvB8gA)

**Comment by maziac** [comment]
Actually the hex-hover-converter can deal with $, see e.g.:
![Bildschirmfoto 2024-12-15 um 12 51 29](https://github.com/user-attachments/assets/8de8f72d-750c-4ec6-996e-9eee1e41ea99)

The % is unfortunately very ambigous, so I wouldn't use that.

**Comment by rpolasek** [comment]
Could you write any ambiguous example with `%`, please? I'll try to help and find out a solution.

**Comment by maziac** [comment]
% is used as remainder in many programming languages.

**Comment by rpolasek** [comment]
I'm sorry I hasn't got that. What do you mean by a "reminder"?

**Comment by rpolasek** [comment]
> Actually the hex-hover-converter can deal with $

what about that? is it ok?
![hex-8000](https://github.com/user-attachments/assets/e4a2ad9d-7456-4669-a97c-62e1888575e9)

**Comment by maziac** [comment]
> I'm sorry I hasn't got that. What do you mean by a "reminder"?

"remainder": e.g. x = 10 % 8
which would result in 2.

The picture is OK:
First column shows conversions if 8000 is interpreted as decimal (bold).
Second column if interpreted as negative hex.
Third column if interpreted as positive hex.

**Comment by rpolasek** [comment]
well, ambiguous of `%` can be solved by using the right initial regular expression which checks if the mouse is hover a number but I understand you've just decided not to do that. I'll write my own extension. Thanks for your discussion.

**Comment by maziac** [comment]
E.g. imagine "% 10":
- could be binary 2
- or remainder by 10

"I'll write my own extension."
Yes, maybe the best choice. Feel free to fork the hex-hover-converter if you like.
