### ISSUE TITLE
Feature request: Support custom hex format

### ISSUE THREAD

**Issue by nikhenri** [maziac/hex-hover-converter#3]
Hi,
I am a FPGA designer and I found your extensions very useful.
The problem is when I m writing HEX in SytemVerilog, I don't use 0x prefix so the extension doesn't work

This is how a HEX is done in SystemVerilog
![image](https://user-images.githubusercontent.com/61157967/116572963-670a5780-a8da-11eb-84e9-255215843d86.png)

Do you think it would be possible to add the support of this prefix ?
Thank you

**Comment by maziac** [comment]
Is the prefix a sole h or is it a 'h   ?

**Comment by nikhenri** [comment]
**'** give the base, so the **'h** is the whole prefix.

I don't know your level of motivation, but there is also the 'b that is a prefix for binary string, ex: a<= 'b1010

Here a document explaining the format in details:
http://web.engr.oregonstate.edu/~traylor/ece474/beamer_lectures/verilog_number_literals.pdf

**Comment by maziac** [comment]
Could you please try this version:
https://github.com/maziac/hex-hover-converter/releases/tag/v1.2.0
It should allow decoding verily hex and binary numbers. (But not **d**ecimal format)

**Comment by nikhenri** [comment]
Hex seem to work correctly, with or without size
![image](https://user-images.githubusercontent.com/61157967/116730896-08ff7200-a9b7-11eb-95e2-cea6d8338f22.png)

![image](https://user-images.githubusercontent.com/61157967/116730908-0e5cbc80-a9b7-11eb-866a-5683982ecc94.png)

The binary is seen as hex, with or without size
![image](https://user-images.githubusercontent.com/61157967/116730996-292f3100-a9b7-11eb-9417-803c6a92c900.png)
expected: Dec: 4, Hex: 4
I think it's a display bug

Dont worry about 'd since if you don't write prefix, it's treaded as decimal
'd9 == 9

**Comment by maziac** [comment]
Could you please try https://github.com/maziac/hex-hover-converter/releases/tag/v1.2.1

d should be supported and for b it should not display the hex anymore.

**Comment by nikhenri** [comment]
Work perfectly!
Thank you
