### ISSUE TITLE
Work for constants?

### ISSUE THREAD

**Issue by rotateLeft** [maziac/hex-hover-converter#7]
Can this be extended to also convert named constants?

Ie, define constant (Python):

FOOBARBAZ = 0xEA0000

Hover over, with this extension installed, tooltip will show:

(constant) FOOBARBAZ: Literal[15335424]

**Comment by maziac** [comment]
The hex-hover-converter converts only numbers.
It is programming language agnostic.

And I want to keep it simple.

So I don't think I will ever support constants.
But you can, of course, fork the repository and implement yourself.
