### ISSUE TITLE
Do not show for Numbers without any prefix

### ISSUE THREAD

**Issue by Vendicated** [maziac/hex-hover-converter#9]
This could also be configurable if someone needs this without prefix

In any case, it's wrongfully adding hovers to things like methods, and it would be cool to not have these false positives
![image](https://user-images.githubusercontent.com/45497981/200115295-0594f6d0-7f57-49fa-8f8d-a3fd9189f7d1.png)

**Comment by Vendicated** [comment]
![image](https://user-images.githubusercontent.com/45497981/200116146-f1062149-d90e-472b-a470-0870cde29f4e.png)

**Comment by maziac** [comment]
Yeah, actually theses could also be hex numbers, therefore the false positives. But I, of course, see your point.
Maybe some options are possible, e.g.:
- count of digits is 2, 4, 8, 16 etc
- not starting with dot

The "F" is difficult because the "l" is interpreted as "long" (maybe the check need to be extended that the "l" is not followed by something ...)

**Comment by ArjixWasTaken** [comment]
i think it is safe to assume that you can't call a number as a function...
(well, in the screenshot it is a function declaration and not a call, but oh well, doesn't change much)

so maybe edit the regex [here](https://github.com/maziac/hex-hover-converter/blob/master/src/extension.ts#L6)
![image](https://user-images.githubusercontent.com/53124886/200117800-6f053fea-cf24-4646-81d9-ff0f3dd78afb.png)

```javascript
/(?<!\w)[0-9a-fA-FbhxulULHB_]+\b(?!\()/
```

**Comment by ArjixWasTaken** [comment]
I haven't tested this regex that much, so please take it with a grain of salt.

**Comment by ArjixWasTaken** [comment]
My suggestion doesn't fix the false positives when declaring/using a variable though, and I doubt there is a language-agnostic way of doing that...

**Comment by maziac** [comment]
Maybe there could be an option for the mode: "lazy" and "strict".

**Comment by maziac** [comment]
I have thought about your original idea.

What about e.g.:
"; Write to address 1000h(audio_port)."
One could argue: there should be a space between h and (.
But if not ...

Not sure if this problem can really be solved without more context.

Maybe simply fork the project and use an regex that fits better for you.

Do you mind if I close this issue?
